program: proteinworkshop/train.py
method: grid
name: baseline_gc_prediction_egnn
metric:
  goal: minimize
  name: val/loss/total

parameters:
  task:
    values: [multiclass_graph_classification]
  dataset:
    values: [fold_fold] #[fold_family, fold_superfamily, fold_fold]
  encoder:
    values: [egnn] #, unet_schnet3, unet_schnet_s] #[schnet, unet_schnet, unet_schnet_2]  # Add your new model here
  optimiser.optimizer.lr:
    value: 0.0001 #0.001 #0.0003 #0.0001
  features:
    values: [ca_bb] #[ca_base, ca_seq, ca_angles, ca_bb, ca_sc]
  scheduler:
    values: [plateau]
  extras.enforce_tags:
    value: False
  +aux_task:
    values: [none]
  trainer.max_epochs:
    value: 150
  test:
    value: True

command:
  - ${env}
  - HYDRA_FULL_ERROR=1
  - WANDB_START_METHOD=thread
  - python
  - ${program}
  - ${args_no_hyphens}
